### ISSUE TITLE
Blinkenlights cannot be used with '-l' option

### ISSUE THREAD

**Issue by iliastsi** [OfflineIMAP/offlineimap#293]
When using Blinkenlights UI alongside the '-l' option, OfflineIMAP crashes with AttributeError:

```shell
$ ./offlineimap.py -c offlineimap.conf.minimal -u blinkenlights -l foo 
Traceback (most recent call last):
  File "./offlineimap.py", line 36, in <module>
    oi.run()
  File "/tmp/offlineimap/offlineimap/init.py", line 50, in run
    options, args = self.__parse_cmd_options()
  File "/tmp/offlineimap/offlineimap/init.py", line 205, in __parse_cmd_options
    self.ui.setlogfile(options.logfile)
  File "/tmp/offlineimap/offlineimap/ui/UIBase.py", line 119, in setlogfile
    self.logger.info(msg)
  File "/usr/lib/python2.7/logging/__init__.py", line 1159, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 751, in handle
    self.emit(record)
  File "/tmp/offlineimap/offlineimap/ui/Curses.py", line 305, in emit
    color = self.ui.gettf().curses_color
AttributeError: 'CursesLogHandler' object has no attribute 'ui'
```

This is a regression since it used to work on version 6.3.4.
Doing a *git bisect* shows that the bug was introduced by the following commit:

```patch
commit a1dc76ae917d93d0c387bbd506faea3487211a6c
Author: Sebastian Spaeth <Sebastian@SSpaeth.de>
Date:   Fri Aug 31 23:11:11 2012 +0200

    Don't output initial blurb in "quiet" mode
    
    When logging to a file using the -l switch, we would still write an initial
    banner to the file. This was never intended. Quiet should be really quiet
    unless it experiences an error. Simplify the logging statement, to do nothing
    if logevel is set to "WARNING" aka quiet.
    
    Signed-off-by: Sebastian Spaeth <Sebastian@SSpaeth.de>

diff --git a/offlineimap/ui/UIBase.py b/offlineimap/ui/UIBase.py
index fab3818..2c30b94 100644
--- a/offlineimap/ui/UIBase.py
+++ b/offlineimap/ui/UIBase.py
@@ -88,7 +88,6 @@ class UIBase(object):
     def setlogfile(self, logfile):
         """Create file handler which logs to file"""
         fh = logging.FileHandler(logfile, 'at')
-        #fh.setLevel(logging.DEBUG)
         file_formatter = logging.Formatter("%(asctime)s %(levelname)s: "
                          "%(message)s", '%Y-%m-%d %H:%M:%S')
         fh.setFormatter(file_formatter)
@@ -98,9 +97,7 @@ class UIBase(object):
         msg = "OfflineImap %s starting...\n  Python: %s Platform: %s\n  "\
               "Args: %s" % (offlineimap.__version__, p_ver, sys.platform,
                             " ".join(sys.argv))
-        record = logging.LogRecord('OfflineImap', logging.INFO, __file__,
-                                   None, msg, None, None)
-        fh.emit(record)
+        self.logger.info(msg)
 
     def _msg(self, msg):
         """Display a message."""
```

**Comment by nicolas33** [comment]
Thanks. However, I guess this git bisect is wrong because the issue is about the missing `ui` attribute in `offlineimap/ui/Curses.py`.

**Comment by iliastsi** [comment]
You are right that the issue is about the missing ```ui``` attribute in ```offlineimap/ui/Curses.py``` but the git bisect is not wrong. The commit that triggered the bug is the one mentioned above. If I try and revert that, then the above command works.

**Comment by nicolas33** [comment]
Ok, reverted. Thanks.
